version: '3.8'

services:
  steve-cms-app:
    build:
      context: .
      dockerfile: Dockerfile.cms
    container_name: steve-cms-app
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      default:
      steve-java_default:
      prod_network:
        ipv4_address: 192.168.0.4
    ports:
      - "8080:8080"
    command: /bin/bash -c "php artisan serve --host=0.0.0.0 --port=8080"

  steve-cms-redis:
    image: redis:alpine
    container_name: steve-cms-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - default
      - steve-java_default

volumes:
  redis-data:
    external: true

networks:
  default:
    name: steve-cms_default
  steve-java_default:
    external: true
  prod_network:
    external: true
